//
// Created by simon on 2017-04-29.
//

#ifndef HALLSOFBUBBA_OBJECTIDENTIFIERS_H
#define HALLSOFBUBBA_OBJECTIDENTIFIERS_H

enum ObjectIdentifiers : int {
    PLAYER_IDENTIFIER,
    ENEMY_IDENTIFIER,
    PLAYER_SPAWNED_BULLET,
    ENEMY_SPAWNED_BULLET,
    DOOR_IDENTIFIER
};

#endif //HALLSOFBUBBA_OBJECTIDENTIFIERS_H
